=== justinjohn83/utils-java/utils/src/main/java/com/gamesalutes/utils/arg/args.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name = "config" type = "Config"/>
  
  
    <xsd:complexType name="Argument">
    	<xsd:sequence>
    		<xsd:element name = "value" type = "xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
    	 <xsd:attribute name = "option" type = "xsd:string" use = "optional" />
    	 <xsd:attribute name = "value" type = "xsd:string" use = "optional" />
    </xsd:complexType>
    
    <xsd:complexType name="Module">
    <xsd:sequence>
  		<xsd:element name = "arg" type = "Argument" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name = "class" type = "xsd:string" use = "required" />
    <xsd:attribute name = "order" type = "xsd:positiveInteger" use = "required" />
    <xsd:attribute name = "skip" type = "xsd:boolean" use = "optional" default = "false" />
  </xsd:complexType>
  
  <xsd:complexType name = "Config">
  	<xsd:sequence>
  		<xsd:element name = "module" type = "Module" minOccurs = "0" maxOccurs = "unbounded" />
  	</xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== justinjohn83/utils-java/utils/src/test/java/com/gamesalutes/utils/arg/test_args.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="args.xsd">

<module class="com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassA" order = "1" />
<module class="com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassB" order = "6">
	<!-- separates data center name from cluster name -->
	<arg option = "dn" />
	<arg option = "cluster_sep" value = ":"/>
	<!--  separates data center/cluster pair from optional host import type  -->
	<arg option = "datacenters" value = "consoles.dat"/>
	<arg value = "data/vi_console.txt"/>
	<arg value = "logs/vi.log" />
</module>
<module class = "com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassA" order = "3">
	<arg option = "f" value = "dns_zones.dat"/>
</module>
<module class = "com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassC" order = "4">
	<arg option = "O" value = "logs/hi.log"/>
	<arg value = "data/him.csv"/>
</module>
<module class = "com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassC" order = "5" skip = "true">
	<arg option = "O" value = "logs/hi.log"/>
	<arg value = "data/him.csv"/>
</module>
<module class = "com.gamesalutes.utils.arg.ProgramArgsReaderTest$ClassB" order = "2">
	<arg option = "a" value = "test 1"/>
	<arg>
	   <value>test</value>
	   <value>test 2</value>
	   <value>test3</value>
	 </arg>
</module>
	
</config>
